// ----------------------------------------------------------------------------------------------------
// File Name: Status.cs
// Project: Orchestra.Framework.Utilities
// Copyright (c) Thales, 2010 - 2012. All rights reserved.
// ----------------------------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace Orchestra.Framework
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Runtime.InteropServices;
    using System.Xml.Schema;
    using System.Xml.Serialization;

    ///<summary>
    /// This class implements the Status Definition management
    ///</summary>
    /// <remarks>Xml file is compliant with Status.xsd</remarks>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_25/Status")]
    [XmlRoot("statusDefinition", Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_25/Status",
        IsNullable = false)]
    public partial class StatusDefinition
    {
        private Status statusField;

        #region IStatusDefinition Members
        ///<summary>
        /// Returns the Root Status (See <see cref="Status"/>)
        ///</summary>
        [XmlElement(Form = XmlSchemaForm.Unqualified)]
        public Status status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        #endregion
    }

    ///<summary>
    /// This class implements the Status management
    ///</summary>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_25/Status")]
    public partial class Status
    {
        private int codeField;

        private bool codeFieldSpecified;
        private string exportFilePathField;
        private string messageField;
        private StatusSeverity severityField;
        private Status[] statusField;
        private string uriField;

        ///<summary>
        /// <c>true</c> if <see cref="code"/> is specified otherwise <c>false</c>
        ///</summary>
        [XmlIgnore]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }

        ///<summary>
        /// Property to get or set children <see cref="Status"/>
        /// <para>Returns an array of <see cref="Status"/></para>
        ///</summary>
        [XmlElement("status", Form = XmlSchemaForm.Unqualified)]
        public Status[] status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        #region IStatus Members
        ///<summary>
        /// Property to get or set the full path of the .gef file
        ///</summary>
        [XmlAttribute]
        public string exportFilePath
        {
            get
            {
                return this.exportFilePathField;
            }
            set
            {
                this.exportFilePathField = value;
            }
        }

        ///<summary>
        /// Property to get or set the <see cref="StatusSeverity"/>
        ///</summary>
        [XmlAttribute]
        public StatusSeverity severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        ///<summary>
        /// Property to get or set message
        ///</summary>
        [XmlAttribute]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        ///<summary>
        /// Property to get or set the Orchestra Uri
        ///</summary>
        [XmlAttribute]
        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }

        ///<summary>
        /// Property to get or set the code
        ///</summary>
        [XmlAttribute]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        #endregion
    }

    /// <summary>
    /// Status severity enum.
    /// </summary>
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [XmlType(AnonymousType = true, Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_25/Status")]
    [ComVisible(true)]
    public enum StatusSeverity
    {
        ///<summary>
        /// Status severity constant (value 0) indicating this status represents the nominal case.
        ///</summary>
        OK = 0,

        ///<summary>
        /// Status type severity (bit mask, value 1) indicating this status is informational only.
        ///</summary>
        INFO = 1,

        ///<summary>
        /// Status type severity (bit mask, value 2) indicating this status represents a warning.
        ///</summary>
        WARNING = 2,

        ///<summary>
        /// Status type severity (bit mask, value 4) indicating this status represents an error.
        ///</summary>
        ERROR = 4
    }
}