//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace Orchestra.Framework.VariableManager.VariableManagerServer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VariableManagerSoapBinding", Namespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(EnvironmentValueWS))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(EnvironmentWS))]
    public partial class VariableManagerWSAdapterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVariableOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllContextNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllVariablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVariablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCurrentContextNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSubstitutedValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback registerAsVariableConsumerOperationCompleted;
        
        private System.Threading.SendOrPostCallback unregisterAsVariableConsumerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllVariablesLocalizedOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVariableLocalizedOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVariablesLocalizedOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVariableArtefactPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVariableConfigurationDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVariableSharedDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVariableTemporaryDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCategorySeparatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback configurationDirectoryUpdatedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VariableManagerWSAdapterService() {
            this.Url = global::Orchestra.Framework.VariableManager.Properties.Settings.Default.Orchestra_Framework_VariableManager_VariableManagerServer_VariableManagerWSAdapterService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getCategoriesCompletedEventHandler getCategoriesCompleted;
        
        /// <remarks/>
        public event getVariableCompletedEventHandler getVariableCompleted;
        
        /// <remarks/>
        public event getAllContextNamesCompletedEventHandler getAllContextNamesCompleted;
        
        /// <remarks/>
        public event getAllVariablesCompletedEventHandler getAllVariablesCompleted;
        
        /// <remarks/>
        public event getVariablesCompletedEventHandler getVariablesCompleted;
        
        /// <remarks/>
        public event getCurrentContextNameCompletedEventHandler getCurrentContextNameCompleted;
        
        /// <remarks/>
        public event getSubstitutedValueCompletedEventHandler getSubstitutedValueCompleted;
        
        /// <remarks/>
        public event registerAsVariableConsumerCompletedEventHandler registerAsVariableConsumerCompleted;
        
        /// <remarks/>
        public event unregisterAsVariableConsumerCompletedEventHandler unregisterAsVariableConsumerCompleted;
        
        /// <remarks/>
        public event getAllVariablesLocalizedCompletedEventHandler getAllVariablesLocalizedCompleted;
        
        /// <remarks/>
        public event getVariableLocalizedCompletedEventHandler getVariableLocalizedCompleted;
        
        /// <remarks/>
        public event getVariablesLocalizedCompletedEventHandler getVariablesLocalizedCompleted;
        
        /// <remarks/>
        public event getVariableArtefactPathCompletedEventHandler getVariableArtefactPathCompleted;
        
        /// <remarks/>
        public event getVariableConfigurationDirectoryCompletedEventHandler getVariableConfigurationDirectoryCompleted;
        
        /// <remarks/>
        public event getVariableSharedDirectoryCompletedEventHandler getVariableSharedDirectoryCompleted;
        
        /// <remarks/>
        public event getVariableTemporaryDirectoryCompletedEventHandler getVariableTemporaryDirectoryCompleted;
        
        /// <remarks/>
        public event getCategorySeparatorCompletedEventHandler getCategorySeparatorCompleted;
        
        /// <remarks/>
        public event configurationDirectoryUpdatedCompletedEventHandler configurationDirectoryUpdatedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("categories")]
        public string[] getCategories(string categoryPath) {
            object[] results = this.Invoke("getCategories", new object[] {
                        categoryPath});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getCategoriesAsync(string categoryPath) {
            this.getCategoriesAsync(categoryPath, null);
        }
        
        /// <remarks/>
        public void getCategoriesAsync(string categoryPath, object userState) {
            if ((this.getCategoriesOperationCompleted == null)) {
                this.getCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCategoriesOperationCompleted);
            }
            this.InvokeAsync("getCategories", new object[] {
                        categoryPath}, this.getCategoriesOperationCompleted, userState);
        }
        
        private void OngetCategoriesOperationCompleted(object arg) {
            if ((this.getCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCategoriesCompleted(this, new getCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variable")]
        public VariableWS getVariable(string variablePath) {
            object[] results = this.Invoke("getVariable", new object[] {
                        variablePath});
            return ((VariableWS)(results[0]));
        }
        
        /// <remarks/>
        public void getVariableAsync(string variablePath) {
            this.getVariableAsync(variablePath, null);
        }
        
        /// <remarks/>
        public void getVariableAsync(string variablePath, object userState) {
            if ((this.getVariableOperationCompleted == null)) {
                this.getVariableOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVariableOperationCompleted);
            }
            this.InvokeAsync("getVariable", new object[] {
                        variablePath}, this.getVariableOperationCompleted, userState);
        }
        
        private void OngetVariableOperationCompleted(object arg) {
            if ((this.getVariableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVariableCompleted(this, new getVariableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("contextNames")]
        public string[] getAllContextNames() {
            object[] results = this.Invoke("getAllContextNames", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllContextNamesAsync() {
            this.getAllContextNamesAsync(null);
        }
        
        /// <remarks/>
        public void getAllContextNamesAsync(object userState) {
            if ((this.getAllContextNamesOperationCompleted == null)) {
                this.getAllContextNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllContextNamesOperationCompleted);
            }
            this.InvokeAsync("getAllContextNames", new object[0], this.getAllContextNamesOperationCompleted, userState);
        }
        
        private void OngetAllContextNamesOperationCompleted(object arg) {
            if ((this.getAllContextNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllContextNamesCompleted(this, new getAllContextNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variables")]
        public VariableWS[] getAllVariables() {
            object[] results = this.Invoke("getAllVariables", new object[0]);
            return ((VariableWS[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllVariablesAsync() {
            this.getAllVariablesAsync(null);
        }
        
        /// <remarks/>
        public void getAllVariablesAsync(object userState) {
            if ((this.getAllVariablesOperationCompleted == null)) {
                this.getAllVariablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllVariablesOperationCompleted);
            }
            this.InvokeAsync("getAllVariables", new object[0], this.getAllVariablesOperationCompleted, userState);
        }
        
        private void OngetAllVariablesOperationCompleted(object arg) {
            if ((this.getAllVariablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllVariablesCompleted(this, new getAllVariablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variables")]
        public VariableWS[] getVariables(string categoryPath) {
            object[] results = this.Invoke("getVariables", new object[] {
                        categoryPath});
            return ((VariableWS[])(results[0]));
        }
        
        /// <remarks/>
        public void getVariablesAsync(string categoryPath) {
            this.getVariablesAsync(categoryPath, null);
        }
        
        /// <remarks/>
        public void getVariablesAsync(string categoryPath, object userState) {
            if ((this.getVariablesOperationCompleted == null)) {
                this.getVariablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVariablesOperationCompleted);
            }
            this.InvokeAsync("getVariables", new object[] {
                        categoryPath}, this.getVariablesOperationCompleted, userState);
        }
        
        private void OngetVariablesOperationCompleted(object arg) {
            if ((this.getVariablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVariablesCompleted(this, new getVariablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("currentContextName")]
        public string getCurrentContextName() {
            object[] results = this.Invoke("getCurrentContextName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCurrentContextNameAsync() {
            this.getCurrentContextNameAsync(null);
        }
        
        /// <remarks/>
        public void getCurrentContextNameAsync(object userState) {
            if ((this.getCurrentContextNameOperationCompleted == null)) {
                this.getCurrentContextNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCurrentContextNameOperationCompleted);
            }
            this.InvokeAsync("getCurrentContextName", new object[0], this.getCurrentContextNameOperationCompleted, userState);
        }
        
        private void OngetCurrentContextNameOperationCompleted(object arg) {
            if ((this.getCurrentContextNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCurrentContextNameCompleted(this, new getCurrentContextNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("value")]
        public string getSubstitutedValue(string variablePath) {
            object[] results = this.Invoke("getSubstitutedValue", new object[] {
                        variablePath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSubstitutedValueAsync(string variablePath) {
            this.getSubstitutedValueAsync(variablePath, null);
        }
        
        /// <remarks/>
        public void getSubstitutedValueAsync(string variablePath, object userState) {
            if ((this.getSubstitutedValueOperationCompleted == null)) {
                this.getSubstitutedValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSubstitutedValueOperationCompleted);
            }
            this.InvokeAsync("getSubstitutedValue", new object[] {
                        variablePath}, this.getSubstitutedValueOperationCompleted, userState);
        }
        
        private void OngetSubstitutedValueOperationCompleted(object arg) {
            if ((this.getSubstitutedValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSubstitutedValueCompleted(this, new getSubstitutedValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        public void registerAsVariableConsumer(string toolInstanceID) {
            this.Invoke("registerAsVariableConsumer", new object[] {
                        toolInstanceID});
        }
        
        /// <remarks/>
        public void registerAsVariableConsumerAsync(string toolInstanceID) {
            this.registerAsVariableConsumerAsync(toolInstanceID, null);
        }
        
        /// <remarks/>
        public void registerAsVariableConsumerAsync(string toolInstanceID, object userState) {
            if ((this.registerAsVariableConsumerOperationCompleted == null)) {
                this.registerAsVariableConsumerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterAsVariableConsumerOperationCompleted);
            }
            this.InvokeAsync("registerAsVariableConsumer", new object[] {
                        toolInstanceID}, this.registerAsVariableConsumerOperationCompleted, userState);
        }
        
        private void OnregisterAsVariableConsumerOperationCompleted(object arg) {
            if ((this.registerAsVariableConsumerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registerAsVariableConsumerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        public void unregisterAsVariableConsumer(string toolInstanceID) {
            this.Invoke("unregisterAsVariableConsumer", new object[] {
                        toolInstanceID});
        }
        
        /// <remarks/>
        public void unregisterAsVariableConsumerAsync(string toolInstanceID) {
            this.unregisterAsVariableConsumerAsync(toolInstanceID, null);
        }
        
        /// <remarks/>
        public void unregisterAsVariableConsumerAsync(string toolInstanceID, object userState) {
            if ((this.unregisterAsVariableConsumerOperationCompleted == null)) {
                this.unregisterAsVariableConsumerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunregisterAsVariableConsumerOperationCompleted);
            }
            this.InvokeAsync("unregisterAsVariableConsumer", new object[] {
                        toolInstanceID}, this.unregisterAsVariableConsumerOperationCompleted, userState);
        }
        
        private void OnunregisterAsVariableConsumerOperationCompleted(object arg) {
            if ((this.unregisterAsVariableConsumerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unregisterAsVariableConsumerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variables")]
        public VariableWS[] getAllVariablesLocalized(string locale) {
            object[] results = this.Invoke("getAllVariablesLocalized", new object[] {
                        locale});
            return ((VariableWS[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllVariablesLocalizedAsync(string locale) {
            this.getAllVariablesLocalizedAsync(locale, null);
        }
        
        /// <remarks/>
        public void getAllVariablesLocalizedAsync(string locale, object userState) {
            if ((this.getAllVariablesLocalizedOperationCompleted == null)) {
                this.getAllVariablesLocalizedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllVariablesLocalizedOperationCompleted);
            }
            this.InvokeAsync("getAllVariablesLocalized", new object[] {
                        locale}, this.getAllVariablesLocalizedOperationCompleted, userState);
        }
        
        private void OngetAllVariablesLocalizedOperationCompleted(object arg) {
            if ((this.getAllVariablesLocalizedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllVariablesLocalizedCompleted(this, new getAllVariablesLocalizedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variable")]
        public VariableWS getVariableLocalized(string variablePath, string locale) {
            object[] results = this.Invoke("getVariableLocalized", new object[] {
                        variablePath,
                        locale});
            return ((VariableWS)(results[0]));
        }
        
        /// <remarks/>
        public void getVariableLocalizedAsync(string variablePath, string locale) {
            this.getVariableLocalizedAsync(variablePath, locale, null);
        }
        
        /// <remarks/>
        public void getVariableLocalizedAsync(string variablePath, string locale, object userState) {
            if ((this.getVariableLocalizedOperationCompleted == null)) {
                this.getVariableLocalizedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVariableLocalizedOperationCompleted);
            }
            this.InvokeAsync("getVariableLocalized", new object[] {
                        variablePath,
                        locale}, this.getVariableLocalizedOperationCompleted, userState);
        }
        
        private void OngetVariableLocalizedOperationCompleted(object arg) {
            if ((this.getVariableLocalizedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVariableLocalizedCompleted(this, new getVariableLocalizedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variables")]
        public VariableWS[] getVariablesLocalized(string categoryPath, string locale) {
            object[] results = this.Invoke("getVariablesLocalized", new object[] {
                        categoryPath,
                        locale});
            return ((VariableWS[])(results[0]));
        }
        
        /// <remarks/>
        public void getVariablesLocalizedAsync(string categoryPath, string locale) {
            this.getVariablesLocalizedAsync(categoryPath, locale, null);
        }
        
        /// <remarks/>
        public void getVariablesLocalizedAsync(string categoryPath, string locale, object userState) {
            if ((this.getVariablesLocalizedOperationCompleted == null)) {
                this.getVariablesLocalizedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVariablesLocalizedOperationCompleted);
            }
            this.InvokeAsync("getVariablesLocalized", new object[] {
                        categoryPath,
                        locale}, this.getVariablesLocalizedOperationCompleted, userState);
        }
        
        private void OngetVariablesLocalizedOperationCompleted(object arg) {
            if ((this.getVariablesLocalizedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVariablesLocalizedCompleted(this, new getVariablesLocalizedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variable")]
        public VariableWS getVariableArtefactPath() {
            object[] results = this.Invoke("getVariableArtefactPath", new object[0]);
            return ((VariableWS)(results[0]));
        }
        
        /// <remarks/>
        public void getVariableArtefactPathAsync() {
            this.getVariableArtefactPathAsync(null);
        }
        
        /// <remarks/>
        public void getVariableArtefactPathAsync(object userState) {
            if ((this.getVariableArtefactPathOperationCompleted == null)) {
                this.getVariableArtefactPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVariableArtefactPathOperationCompleted);
            }
            this.InvokeAsync("getVariableArtefactPath", new object[0], this.getVariableArtefactPathOperationCompleted, userState);
        }
        
        private void OngetVariableArtefactPathOperationCompleted(object arg) {
            if ((this.getVariableArtefactPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVariableArtefactPathCompleted(this, new getVariableArtefactPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variable")]
        public VariableWS getVariableConfigurationDirectory() {
            object[] results = this.Invoke("getVariableConfigurationDirectory", new object[0]);
            return ((VariableWS)(results[0]));
        }
        
        /// <remarks/>
        public void getVariableConfigurationDirectoryAsync() {
            this.getVariableConfigurationDirectoryAsync(null);
        }
        
        /// <remarks/>
        public void getVariableConfigurationDirectoryAsync(object userState) {
            if ((this.getVariableConfigurationDirectoryOperationCompleted == null)) {
                this.getVariableConfigurationDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVariableConfigurationDirectoryOperationCompleted);
            }
            this.InvokeAsync("getVariableConfigurationDirectory", new object[0], this.getVariableConfigurationDirectoryOperationCompleted, userState);
        }
        
        private void OngetVariableConfigurationDirectoryOperationCompleted(object arg) {
            if ((this.getVariableConfigurationDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVariableConfigurationDirectoryCompleted(this, new getVariableConfigurationDirectoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variable")]
        public VariableWS getVariableSharedDirectory() {
            object[] results = this.Invoke("getVariableSharedDirectory", new object[0]);
            return ((VariableWS)(results[0]));
        }
        
        /// <remarks/>
        public void getVariableSharedDirectoryAsync() {
            this.getVariableSharedDirectoryAsync(null);
        }
        
        /// <remarks/>
        public void getVariableSharedDirectoryAsync(object userState) {
            if ((this.getVariableSharedDirectoryOperationCompleted == null)) {
                this.getVariableSharedDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVariableSharedDirectoryOperationCompleted);
            }
            this.InvokeAsync("getVariableSharedDirectory", new object[0], this.getVariableSharedDirectoryOperationCompleted, userState);
        }
        
        private void OngetVariableSharedDirectoryOperationCompleted(object arg) {
            if ((this.getVariableSharedDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVariableSharedDirectoryCompleted(this, new getVariableSharedDirectoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("variable")]
        public VariableWS getVariableTemporaryDirectory() {
            object[] results = this.Invoke("getVariableTemporaryDirectory", new object[0]);
            return ((VariableWS)(results[0]));
        }
        
        /// <remarks/>
        public void getVariableTemporaryDirectoryAsync() {
            this.getVariableTemporaryDirectoryAsync(null);
        }
        
        /// <remarks/>
        public void getVariableTemporaryDirectoryAsync(object userState) {
            if ((this.getVariableTemporaryDirectoryOperationCompleted == null)) {
                this.getVariableTemporaryDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVariableTemporaryDirectoryOperationCompleted);
            }
            this.InvokeAsync("getVariableTemporaryDirectory", new object[0], this.getVariableTemporaryDirectoryOperationCompleted, userState);
        }
        
        private void OngetVariableTemporaryDirectoryOperationCompleted(object arg) {
            if ((this.getVariableTemporaryDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVariableTemporaryDirectoryCompleted(this, new getVariableTemporaryDirectoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
        [return: System.Xml.Serialization.SoapElementAttribute("categorySeparator")]
        public string getCategorySeparator() {
            object[] results = this.Invoke("getCategorySeparator", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCategorySeparatorAsync() {
            this.getCategorySeparatorAsync(null);
        }
        
        /// <remarks/>
        public void getCategorySeparatorAsync(object userState) {
            if ((this.getCategorySeparatorOperationCompleted == null)) {
                this.getCategorySeparatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCategorySeparatorOperationCompleted);
            }
            this.InvokeAsync("getCategorySeparator", new object[0], this.getCategorySeparatorOperationCompleted, userState);
        }
        
        private void OngetCategorySeparatorOperationCompleted(object arg) {
            if ((this.getCategorySeparatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCategorySeparatorCompleted(this, new getCategorySeparatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://com.thalesgroup.orchestra.framework/VariableManager/configurationDirectory" +
            "Updated", RequestNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", ResponseNamespace="http://com.thalesgroup.orchestra.framework/VariableManager", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("deltaState", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DeltaState[] configurationDirectoryUpdated(string confDirPath, [System.Xml.Serialization.XmlArrayItemAttribute("delta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] ConfDirDelta[] deltas) {
            object[] results = this.Invoke("configurationDirectoryUpdated", new object[] {
                        confDirPath,
                        deltas});
            return ((DeltaState[])(results[0]));
        }
        
        /// <remarks/>
        public void configurationDirectoryUpdatedAsync(string confDirPath, ConfDirDelta[] deltas) {
            this.configurationDirectoryUpdatedAsync(confDirPath, deltas, null);
        }
        
        /// <remarks/>
        public void configurationDirectoryUpdatedAsync(string confDirPath, ConfDirDelta[] deltas, object userState) {
            if ((this.configurationDirectoryUpdatedOperationCompleted == null)) {
                this.configurationDirectoryUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfigurationDirectoryUpdatedOperationCompleted);
            }
            this.InvokeAsync("configurationDirectoryUpdated", new object[] {
                        confDirPath,
                        deltas}, this.configurationDirectoryUpdatedOperationCompleted, userState);
        }
        
        private void OnconfigurationDirectoryUpdatedOperationCompleted(object arg) {
            if ((this.configurationDirectoryUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.configurationDirectoryUpdatedCompleted(this, new configurationDirectoryUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
    public partial class ConfDirDelta {
        
        private string subPathField;
        
        private ConfDirDeltaDeltaType deltaTypeField;
        
        private bool deltaTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subPath {
            get {
                return this.subPathField;
            }
            set {
                this.subPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConfDirDeltaDeltaType deltaType {
            get {
                return this.deltaTypeField;
            }
            set {
                this.deltaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deltaTypeSpecified {
            get {
                return this.deltaTypeFieldSpecified;
            }
            set {
                this.deltaTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
    public enum ConfDirDeltaDeltaType {
        
        /// <remarks/>
        ADD,
        
        /// <remarks/>
        DEL,
        
        /// <remarks/>
        MOD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
    public partial class DeltaState {
        
        private ConfDirDelta deltaField;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConfDirDelta delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(EnvironmentVariableWS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
    public partial class VariableWS {
        
        private string descriptionField;
        
        private bool multiValuedField;
        
        private string nameField;
        
        private string pathField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool multiValued {
            get {
                return this.multiValuedField;
            }
            set {
                this.multiValuedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
    public partial class EnvironmentValueWS {
        
        private string keyField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
    public partial class EnvironmentWS {
        
        private string environmentIdField;
        
        private string environmentCategoryField;
        
        private EnvironmentValueWS[] valuesField;
        
        /// <remarks/>
        public string environmentId {
            get {
                return this.environmentIdField;
            }
            set {
                this.environmentIdField = value;
            }
        }
        
        /// <remarks/>
        public string environmentCategory {
            get {
                return this.environmentCategoryField;
            }
            set {
                this.environmentCategoryField = value;
            }
        }
        
        /// <remarks/>
        public EnvironmentValueWS[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://com.thalesgroup.orchestra.framework/VariableManager")]
    public partial class EnvironmentVariableWS : VariableWS {
        
        private EnvironmentWS[] environmentsField;
        
        /// <remarks/>
        public EnvironmentWS[] environments {
            get {
                return this.environmentsField;
            }
            set {
                this.environmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getCategoriesCompletedEventHandler(object sender, getCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVariableCompletedEventHandler(object sender, getVariableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVariableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVariableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getAllContextNamesCompletedEventHandler(object sender, getAllContextNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllContextNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllContextNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getAllVariablesCompletedEventHandler(object sender, getAllVariablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllVariablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllVariablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVariablesCompletedEventHandler(object sender, getVariablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVariablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVariablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getCurrentContextNameCompletedEventHandler(object sender, getCurrentContextNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCurrentContextNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCurrentContextNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getSubstitutedValueCompletedEventHandler(object sender, getSubstitutedValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSubstitutedValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSubstitutedValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void registerAsVariableConsumerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void unregisterAsVariableConsumerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getAllVariablesLocalizedCompletedEventHandler(object sender, getAllVariablesLocalizedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllVariablesLocalizedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllVariablesLocalizedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVariableLocalizedCompletedEventHandler(object sender, getVariableLocalizedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVariableLocalizedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVariableLocalizedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVariablesLocalizedCompletedEventHandler(object sender, getVariablesLocalizedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVariablesLocalizedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVariablesLocalizedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVariableArtefactPathCompletedEventHandler(object sender, getVariableArtefactPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVariableArtefactPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVariableArtefactPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVariableConfigurationDirectoryCompletedEventHandler(object sender, getVariableConfigurationDirectoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVariableConfigurationDirectoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVariableConfigurationDirectoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVariableSharedDirectoryCompletedEventHandler(object sender, getVariableSharedDirectoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVariableSharedDirectoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVariableSharedDirectoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVariableTemporaryDirectoryCompletedEventHandler(object sender, getVariableTemporaryDirectoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVariableTemporaryDirectoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVariableTemporaryDirectoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariableWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariableWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getCategorySeparatorCompletedEventHandler(object sender, getCategorySeparatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCategorySeparatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCategorySeparatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void configurationDirectoryUpdatedCompletedEventHandler(object sender, configurationDirectoryUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class configurationDirectoryUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal configurationDirectoryUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeltaState[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeltaState[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591