//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orchestra.Framework.Connector.Doors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orchestra.Framework.Connector.Doors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors.
        /// </summary>
        internal static string ContextConnector_ToolName_Doors {
            get {
                return ResourceManager.GetString("ContextConnector_ToolName_Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception!
        ///Message:
        ///{0}
        ///Call stack:
        ///{1}.
        /// </summary>
        internal static string E61006 {
            get {
                return ResourceManager.GetString("E61006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to parse input parameter!.
        /// </summary>
        internal static string E61012 {
            get {
                return ResourceManager.GetString("E61012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command: &quot;{0}&quot; is not yet implemented!.
        /// </summary>
        internal static string E64000 {
            get {
                return ResourceManager.GetString("E64000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented command!.
        /// </summary>
        internal static string E64000_01 {
            get {
                return ResourceManager.GetString("E64000_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file: {0} is not found!.
        /// </summary>
        internal static string E64001_01 {
            get {
                return ResourceManager.GetString("E64001_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object type Module is not found in file: {0}.
        /// </summary>
        internal static string E64001_02 {
            get {
                return ResourceManager.GetString("E64001_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;isExpandable&quot; for Module is not found in file: {0}.
        /// </summary>
        internal static string E64001_03 {
            get {
                return ResourceManager.GetString("E64001_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file: {0} is not found!.
        /// </summary>
        internal static string E64002 {
            get {
                return ResourceManager.GetString("E64002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rootArtefactPath is null!.
        /// </summary>
        internal static string E64003 {
            get {
                return ResourceManager.GetString("E64003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root artefact {0} is not found..
        /// </summary>
        internal static string E64004 {
            get {
                return ResourceManager.GetString("E64004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to determine directory containing file: {0}.
        /// </summary>
        internal static string E64005 {
            get {
                return ResourceManager.GetString("E64005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Connector Doors Status file doesn&apos;t exists!
        ///This error occurs when:
        ///- No Doors license available or
        ///- Database protocol version mismatch.
        ///- The login/password is invalid.
        ///- A unhandled Dxl exception is raised..
        /// </summary>
        internal static string E64006 {
            get {
                return ResourceManager.GetString("E64006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while executing the dxl command: {0}.
        /// </summary>
        internal static string E64007 {
            get {
                return ResourceManager.GetString("E64007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To migrate this uri (module not identified by an Orchestra Module Id),
        ///the Doors artefact &quot;{0}&quot; must be declared into the current context..
        /// </summary>
        internal static string E64008 {
            get {
                return ResourceManager.GetString("E64008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while creating the dxl script:
        ///{0}.
        /// </summary>
        internal static string E64010 {
            get {
                return ResourceManager.GetString("E64010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Doors executable is not found at the following location:
        ///{0}
        ///Verify the current context!.
        /// </summary>
        internal static string E64011 {
            get {
                return ResourceManager.GetString("E64011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Artefact..
        /// </summary>
        internal static string E64012 {
            get {
                return ResourceManager.GetString("E64012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; doesn&apos;t exists..
        /// </summary>
        internal static string E64014 {
            get {
                return ResourceManager.GetString("E64014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors is not accessible (may be Doors credentials window is opened), try later..
        /// </summary>
        internal static string E64015 {
            get {
                return ResourceManager.GetString("E64015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of the Doors Connector is corrupted.
        ///Please contact the Orchestra Support.
        ///The Doors executable is running with Addins located in {0}.
        /// </summary>
        internal static string E64078 {
            get {
                return ResourceManager.GetString("E64078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Doors process has been terminated abnormally..
        /// </summary>
        internal static string E64081 {
            get {
                return ResourceManager.GetString("E64081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple instances of DOORS are open. Unable to connect to the correct instance. Please, close all instances of DOORS..
        /// </summary>
        internal static string E64082 {
            get {
                return ResourceManager.GetString("E64082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Orchestra Framework is not started!
        ///Please start it!.
        /// </summary>
        internal static string E64083 {
            get {
                return ResourceManager.GetString("E64083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors Path not found!
        ///Verify the current context..
        /// </summary>
        internal static string E64084 {
            get {
                return ResourceManager.GetString("E64084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Doors connector does not support any more the .doors file. Please refer to the SUM Doors Connector for migration..
        /// </summary>
        internal static string E64086 {
            get {
                return ResourceManager.GetString("E64086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri: {0} not use Orchestra Module Id, migrate your project..
        /// </summary>
        internal static string E70000 {
            get {
                return ResourceManager.GetString("E70000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string sResult
        ///sResult = (getenv(&quot;DOORSDATA&quot;)) &quot;\n&quot; (getenv(&quot;DOORSADDINS&quot;)) &quot;\n&quot; (getenv(&quot;ADDINS&quot;)) &quot;\n&quot; (getenv(&quot;DOORSATTRIBUTEADDINS&quot;)) &quot;\n&quot; (getenv(&quot;DOORSDEFOPENMODE&quot;)) &quot;\n&quot; (getenv(&quot;DOORSDEFOPENLINKMODE&quot;)) &quot;\n&quot; (getenv(&quot;DOORSLAYOUTADDINS&quot;)) &quot;\n&quot; (getenv(&quot;DOORSLOCALDATA&quot;)) &quot;\n&quot; (getenv(&quot;DOORSLOGFILE&quot;)) &quot;\n&quot; (getenv(&quot;DOORSVERSION&quot;))
        ///oleSetResult(sResult).
        /// </summary>
        internal static string GetDoorsParameters {
            get {
                return ResourceManager.GetString("GetDoorsParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login prompt has been canceled!.
        /// </summary>
        internal static string W64009 {
            get {
                return ResourceManager.GetString("W64009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing database parameter!.
        /// </summary>
        internal static string W64085 {
            get {
                return ResourceManager.GetString("W64085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing autologin parameter!.
        /// </summary>
        internal static string W64086 {
            get {
                return ResourceManager.GetString("W64086", resourceCulture);
            }
        }
    }
}
