// ----------------------------------------------------------------------------------------------------
// File Name: Gef.cs
// Project: Orchestra.Framework.Utilities
// Copyright (c) Thales, 2014 - 2014. All rights reserved.
// ----------------------------------------------------------------------------------------------------

namespace Orchestra.Framework.Utilities
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Xml.Schema;
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    //   

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    [XmlRoot(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef", IsNullable = false)]
    public class GEF
    {
        /// <remarks/>
        [XmlArray(Form = XmlSchemaForm.Unqualified)]
        [XmlArrayItem("ELEMENT", Form = XmlSchemaForm.Unqualified, IsNullable = false)]
        public Element[] GENERIC_EXPORT_FORMAT { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class Element
    {
        /// <remarks/>
        [XmlElement("DESCRIPTION", typeof(Description), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("ELEMENT", typeof(Element), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("FILE_REFERENCE", typeof(FileReference), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("LINKS_TO_ARTIFACTS", typeof(LinksToArtifacts), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("LINKS_TO_ELEMENTS", typeof(LinksToElements), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("PROPERTIES", typeof(Properties), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("VERSION", typeof(Version), Form = XmlSchemaForm.Unqualified)]
        public object[] Items { get; set; }

        /// <remarks/>
        [XmlAttribute("type")]
        public string Type { get; set; }

        /// <remarks/>
        [XmlAttribute("label")]
        public string Label { get; set; }

        /// <remarks/>
        [XmlAttribute("uri")]
        public string Uri { get; set; }

        /// <remarks/>
        [XmlAttribute("hash")]
        public string Hash { get; set; }

        /// <remarks/>
        [XmlAttribute("fullName")]
        public string FullName { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class Description
    {
        /// <remarks/>
        [XmlElement("FILE_REFERENCE", typeof(FileReference), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("TEXTUAL_DESCRIPTION", typeof(TextualDescription), Form = XmlSchemaForm.Unqualified)]
        public object[] Items { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class FileReference
    {
        /// <remarks/>
        [XmlAttribute("mimeType")]
        public string MimeType { get; set; }

        /// <remarks/>
        [XmlAttribute("url")]
        public string Url { get; set; }

        /// <remarks/>
        [XmlAttribute("nature")]
        public string Nature { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class LinksToElements
    {
        /// <remarks/>
        [XmlElement("ELEMENT_REFERENCE", Form = XmlSchemaForm.Unqualified)]
        public ElementReference[] ElementReference { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class ElementReference : Reference
    {
        /// <remarks/>
        [XmlAttribute("label")]
        public string Label { get; set; }

        /// <remarks/>
        [XmlAttribute("fullName")]
        public string FullName { get; set; }
    }

    /// <remarks/>
    [XmlInclude(typeof(ElementReference))]
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class Reference
    {
        /// <remarks/>
        [XmlAttribute("uri")]
        public string Uri { get; set; }

        /// <remarks/>
        [XmlAttribute("linkType")]
        public string LinkType { get; set; }

        /// <remarks/>
        [XmlAttribute("linkDirection")]
        public LinkDirection LinkDirection { get; set; }

        /// <remarks/>
        [XmlIgnore]
        public bool LinkDirectionSpecified { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public enum LinkDirection
    {
        /// <remarks/>
        @in,

        /// <remarks/>
        @out,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class LinksToArtifacts
    {
        /// <remarks/>
        [XmlElement("ARTIFACT_REFERENCE", Form = XmlSchemaForm.Unqualified)]
        public Reference[] ArtifactReference { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class MpropertyValue
    {
        /// <remarks/>
        [XmlText]
        public string[] Text { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class Mproperty
    {
        /// <remarks/>
        [XmlElement("VALUES", Form = XmlSchemaForm.Unqualified)]
        public MpropertyValue[] Values { get; set; }

        /// <remarks/>
        [XmlAttribute("name")]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute("type")]
        public string Type { get; set; }

        /// <remarks/>
        [XmlAttribute("nature")]
        public string Nature { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class Property
    {
        /// <remarks/>
        [XmlAttribute("name")]
        public string Name { get; set; }

        /// <remarks/>
        [XmlAttribute("type")]
        public string Type { get; set; }

        /// <remarks/>
        [XmlAttribute("nature")]
        public string Nature { get; set; }

        /// <remarks/>
        [XmlText]
        public string[] Text { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class Properties
    {
        /// <remarks/>
        [XmlElement("MPROPERTY", typeof(Mproperty), Form = XmlSchemaForm.Unqualified)]
        [XmlElement("PROPERTY", typeof(Property), Form = XmlSchemaForm.Unqualified)]
        public object[] Property { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class Version
    {
        /// <remarks/>
        [XmlAttribute("filePath")]
        public string FilePath { get; set; }

        /// <remarks/>
        [XmlAttribute]
        public string version { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.thalesgroup.com/orchestra/framework/4_0_24/Gef")]
    public class TextualDescription
    {
        /// <remarks/>
        [XmlAttribute("type")]
        public string Type { get; set; }

        /// <remarks/>
        [XmlText]
        public string[] Text { get; set; }
    }
}